# Generated by Django 5.2.4 on 2025-07-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ambassadores/')),
            ],
            options={
                'verbose_name': 'Амбасадоры',
                'verbose_name_plural': 'Амбасадоры',
            },
        ),
        migrations.CreateModel(
            name='Our_supports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_supports/')),
            ],
            options={
                'verbose_name': 'Нас поддерживают',
                'verbose_name_plural': 'нас поддерживают',
            },
        ),
    ]
